### ISSUE TITLE
advanced search fields: With the latest version I don't get any results

### ISSUE THREAD

**Issue by pmario** [kookma/TW-Search#1] opened 2022-01-13 08:32 UTC
With the latest demo I don't get a result. I have to change the selection first.
To reproduce

 - Reload the page
 - search for term: "fields"
 - -> no results
 - I have to deactivate the "all" filter and select "title" "text" fields

I would expect, that "title" and "text" are preselected, similar to the TW default setting

**Comment by kookma** [comment] 2022-01-13 18:19
Thank you Mario!
I confirm this is a bug! The issue is with default selection! 

* It is expected to use `*all -[excluded]` as default
* and also show nothing if user uncheck the  `*all -[excluded]`

I address this in v0.7.0 will be pushed within an hour!

**Comment by kookma** [comment] 2022-01-13 19:57
Fixed in v.0.7.0

**Closed as completed by kookma** 2022-01-13 19:57 UTC
